name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Validate SSG compatibility
        run: bun ./butterfly-cli/cli/index.ts validate --source assets

      - name: Test build
        run: bun ./butterfly-cli/cli/index.ts build --source assets --output dist

      - name: List generated files
        run: ls -la dist/
